name: Deploy to Vercel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Remove env variables, let Vercel CLI handle project detection

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Ruby 3.1.4
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.4
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Build Jekyll site
      run: bundle exec jekyll build
      env:
        JEKYLL_ENV: production

    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Create Vercel project configuration
      run: |
        mkdir -p .vercel
        echo '{"projectId":"${{ secrets.VERCEL_PROJECT_ID }}","orgId":null}' > .vercel/project.json

    - name: Deploy to Vercel (Preview)
      if: github.event_name == 'pull_request'
      run: vercel deploy --token=${{ secrets.VERCEL_TOKEN }}

    - name: Deploy to Vercel (Production)
      if: github.ref == 'refs/heads/main'
      run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} 